### ISSUE TITLE
(BUG)[ My Home version 1.0 ]When I connect to WiFi Internet, the application is crashing

### ISSUE THREAD

**Issue by XAMIR555** [ZeevoX/MyHome#11]
#### Project Information
* Repository-----------:[Here](https://github.com/ZeevoX/MyHome)
* Project Name---------:  [MyHome](https://github.com/ZeevoX/MyHome/releases)
* Publisher------------:  [Timothy Langer](https://github.com/ZeevoX)
* My GitHub account----:  [Here](https://github.com/XAMIR555)

#### Expected behavior

When I connect WiFi and use the application, all application options should be used and the application should not be crash.

#### Actual behavior

When I connect to WiFi Internet, the application is crashing And when I close the application again after WiFi connect, the application crashes and does not open.

#### How to reproduce
* [Download ](https://github.com/ZeevoX/MyHome/releases)the application 
* open the application 
* Connect the WiFi
* Note the Bug

* Browser/App version-: 1.0
* Operating system----: 9.0.0

#### Recording Of The Bug
![20190708_151516](https://user-images.githubusercontent.com/49812927/60803076-3a96b180-a12f-11e9-9d1c-86965b902f8d.gif)

# Logcat

<pre><code>07-08 14:59:10.883 20344 20344 E AndroidRuntime: FATAL EXCEPTION: main
07-08 14:59:10.883 20344 20344 E AndroidRuntime: Process: net.zeevox.myhome, PID: 20344
07-08 14:59:10.883 20344 20344 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:917)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:165)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at net.zeevox.myhome.WebSocketUtils.connectWebSocket(WebSocketUtils.java:18)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.refreshData(MainActivity.java:264)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.access$000(MainActivity.java:54)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity$1.run(MainActivity.java:72)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-08 14:59:10.883 20344 20344 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: FATAL EXCEPTION: main
07-08 14:59:13.334 20449 20449 E AndroidRuntime: Process: net.zeevox.myhome, PID: 20449
07-08 14:59:13.334 20449 20449 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:917)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:165)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at net.zeevox.myhome.WebSocketUtils.connectWebSocket(WebSocketUtils.java:18)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.refreshData(MainActivity.java:264)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.access$000(MainActivity.java:54)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity$1.run(MainActivity.java:72)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-08 14:59:13.334 20449 20449 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: FATAL EXCEPTION: main
07-08 14:59:16.443 20541 20541 E AndroidRuntime: Process: net.zeevox.myhome, PID: 20541
07-08 14:59:16.443 20541 20541 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:917)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:165)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at net.zeevox.myhome.WebSocketUtils.connectWebSocket(WebSocketUtils.java:18)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.refreshData(MainActivity.java:264)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.access$000(MainActivity.java:54)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity$1.run(MainActivity.java:72)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-08 14:59:16.443 20541 20541 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: FATAL EXCEPTION: main
07-08 14:59:19.204 20574 20574 E AndroidRuntime: Process: net.zeevox.myhome, PID: 20574
07-08 14:59:19.204 20574 20574 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no colon was found
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1332)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at okhttp3.HttpUrl.get(HttpUrl.java:917)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.java:165)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at net.zeevox.myhome.WebSocketUtils.connectWebSocket(WebSocketUtils.java:18)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.refreshData(MainActivity.java:264)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity.access$000(MainActivity.java:54)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at net.zeevox.myhome.ui.MainActivity$1.run(MainActivity.java:72)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7091)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-08 14:59:19.204 20574 20574 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
</code></pre>

**Comment by ZeevoX** [comment]
Same logcat error as #10
